# Jekyll _config
title: Welcome to topmost.com.au
email: topmost.com.au@gmail.com
description: >
  Topmost.com.au - Don't miss out on cool stuffs.
baseurl: ""
url: "http://topmost.com.au"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","Dockerfile","README.md"]
author: Topmost.com.au Team

gems: [jekyll-paginate, jekyll-feed, jekyll-seo-tag]

collections:
  docs:
    permalink: /:collection/
    output: true
  posts:
    permalink: /:categories/:year/:month/:day/:title.html
    output: true

